"""Generate all data-driven paper figures as pgfplots .tex fragments.

Covers: the MNIST line plots and boxplots (results/mnist_main/), the
CINIC-10/DMOZ/phishing boxplots (results/paper/), the DP figures of
Section 5 (results/dp/mnist/), and the shared method legends. The
pgfplots styles used by every fragment are written to pgfstyle.tex,
which the paper must \\input in its preamble (with pgfplots loaded).

Run from the repository root:
    python3 analysis/make_pgf_figures.py [--paper-dir /path/to/paper/plots]
"""

import argparse
import glob
import json
import os
import pickle
import re
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(__file__))
import pgf_export as pgf

HERE = os.path.dirname(__file__)
RES_MAIN = os.path.join(HERE, "..", "results", "mnist_main")
RES_DP = os.path.join(HERE, "..", "results", "dp", "mnist")
RES_PAPER = os.path.join(HERE, "..", "results", "paper")

ORDER = ["loo", "unweighted", "accuracy", "crh", "entropy", "shapley",
         "regression"]


def write(outdir, name, content):
    with open(os.path.join(outdir, name), "w") as f:
        f.write("% generated by analysis/make_pgf_figures.py\n" + content)
    print("wrote", name)


# --------------------------------------------------------------- MNIST main

def mnist_line(data, sizes, rule, skip=()):
    series, ref = [], []
    for m in ORDER:
        if m in skip:
            continue
        ns = [n for n in sizes if data[n][m][rule]]
        med = [float(np.median(data[n][m][rule])) for n in ns]
        if not ns:
            continue
        if m != "loo":
            ref += med
        style, fill, lab = pgf.METHOD[m]
        series.append((style, fill, lab, ns, med, None))
    span = max(ref) - min(ref)
    pad = max(span * 0.15, 0.05)
    return pgf.line_axis(series, "Number of Models", "Accuracy (\\%)",
                         ymin=min(ref) - pad, ymax=max(ref) + pad)


def mnist_box(data, sizes, rule):
    """Two stacked rows of grouped boxplots (7 ensemble sizes each), so
    that boxes and rank labels remain readable at document font size."""
    ref = np.concatenate([np.asarray(data[n][m][rule])
                          for n in sizes for m in ORDER
                          if m != "loo" and data[n][m][rule]])
    lo = np.percentile(ref, 0.5)
    hi = np.percentile(ref, 99.5)
    pad = (hi - lo) * 0.12
    rows = []
    half = (len(sizes) + 1) // 2
    for chunk in (sizes[:half], sizes[half:]):
        groups = []
        for n in chunk:
            meds = [np.median(data[n][m][rule]) for m in ORDER]
            ranks = len(meds) - np.argsort(np.argsort(meds))
            groups.append((n, [(pgf.METHOD[m][1], data[n][m][rule], int(r))
                               for m, r in zip(ORDER, ranks)]))
        rows.append(pgf.grouped_boxplots(
            groups, "Number of Models", "Accuracy (\\%)",
            width=r"0.99\textwidth", height="4cm", rank_font=r"\tiny",
            ymin=lo - pad, ymax=hi + pad))
    return "\n\\par\\medskip\n".join(rows)


def make_mnist(outdir):
    data = {}
    for path in glob.glob(os.path.join(RES_MAIN, "size_*.json")):
        n = int(re.search(r"size_(\d+)", path).group(1))
        data[n] = json.load(open(path))
    data = dict(sorted(data.items()))
    detail = [n for n in data if n <= 16]
    large = [n for n in data if n > 16]
    for rule, tag in [("borda", "borda"), ("plurality", "mode")]:
        write(outdir, f"{tag}_line_16.tex", mnist_line(data, detail, rule))
        write(outdir, f"{tag}_line_200.tex", mnist_line(
            data, sorted(set(detail[-1:]) | set(large)), rule,
            skip=("loo",)))
        write(outdir, f"{tag}_box_loo_16.tex", mnist_box(data, detail, rule))


# ------------------------------------------------- archived dataset boxplots

def dataset_box(groups_data):
    """groups_data: list of (label, {method: array})."""
    groups = []
    for lab, dd in groups_data:
        meds = [np.median(dd[m]) for m in ORDER]
        ranks = len(meds) - np.argsort(np.argsort(meds))
        groups.append((lab, [(pgf.METHOD[m][1], dd[m], int(r))
                             for m, r in zip(ORDER, ranks)]))
    return pgf.grouped_boxplots(groups, "Number of Models", "Accuracy (\\%)",
                                height=r"0.66\linewidth")


def make_datasets(outdir):
    cinic_sizes = [("_3", 8), ("", 12), ("_2", 16)]
    cinic_rerun = os.path.join(HERE, "..", "results", "cinic_main")
    for tag in ["fl", "di"]:
        per_rule = {"borda": [], "plurality": []}
        for suffix, n in cinic_sizes:
            rerun = os.path.join(cinic_rerun,
                                 f"{tag}_accuracy_dict_ci{suffix}.json")
            d = json.load(open(rerun if os.path.exists(rerun)
                               else os.path.join(
                                   RES_PAPER, "cinic_noise_results",
                                   f"{tag}_accuracy_dict_ci{suffix}.json")))
            for rule in per_rule:
                per_rule[rule].append(
                    (n, {m: np.array(d[m][rule], float) for m in ORDER}))
        for rule in per_rule:
            write(outdir, f"cinic_{tag}_{rule}.tex",
                  dataset_box(per_rule[rule]))
    rerun_dir = {"dmoz": os.path.join(HERE, "..", "results", "dmoz_main"),
                 "phising": os.path.join(HERE, "..", "results",
                                         "phishing_main")}
    for name, sub, sizes in [("dmoz", "dmoz_exps", [3, 5, 7, 10]),
                             ("phising", "phising", [5, 10, 15])]:
        per_rule = {"borda": [], "plurality": []}
        for s in sizes:
            # prefer the rerun with the corrected code, if present
            rerun = os.path.join(rerun_dir[name], f"accuracy_dict_{s}.json")
            if os.path.exists(rerun):
                d = json.load(open(rerun))
            else:
                d = pickle.load(open(os.path.join(
                    RES_PAPER, sub, f"accuracy_dict_{s}.pkl"), "rb"))
            for rule in per_rule:
                per_rule[rule].append(
                    (s, {m: np.array([float(x) for x in d[m][rule]])
                         for m in ORDER}))
        for rule in per_rule:
            write(outdir, f"{name}_{rule}.tex", dataset_box(per_rule[rule]))


# --------------------------------------------------------------- DP figures

# same method sequence as ORDER / the shared legend, for consistency
DP_ORDER = ["loo", "equal", "accuracy", "crh", "entropy_conf",
            "shapley", "regression"]


def make_dp(outdir):
    r = json.load(open(os.path.join(RES_DP, "dp_results.json")))
    eps = r["eps_grid"]

    # D1: mechanisms (own legend inside the axis)
    mech = [("vpeBlue", "vpeBlue", "Vote-count perturbation", "vote_count"),
            ("vpeVermillion", "vpeVermillion", "Output perturbation",
             "output_pert"),
            ("vpeGreen", "vpeGreen", "Randomized response",
             "randomized_response")]
    marks = {"vote_count": "vpeCRH", "output_pert": "vpeLOO",
             "randomized_response": "vpeShapley"}
    series = []
    for _, fill, lab, key in mech:
        d = r["D1"][key]
        series.append((marks[key], fill, lab, eps, d["mean"], d["std"]))
    np_acc = r["nonprivate"]["equal"]["plurality"]
    series.append(("gray, dashed, mark=none", "gray",
                   "Non-private ensemble", [eps[0], eps[-1]],
                   [np_acc, np_acc], None))
    body = pgf.line_axis(series, r"privacy budget $\epsilon$ per query",
                         "test accuracy (\\%)", xmode="log",
                         width=r"0.75\linewidth",
                         height=r"0.5\linewidth",
                         legend_pos="south east")
    write(outdir, "dp_mechanisms.tex", body)

    # D2: exact vs deployable panels (shared legend fragment)
    deploy = {"equal": "vote_count", "accuracy": "vote_count_capped",
              "entropy_conf": "vote_count_capped"}
    for panel, key_of in [("exact", lambda s: f"{s}|vote_count_exactw"),
                          ("deploy",
                           lambda s: f"{s}|{deploy.get(s, 'vote_count')}")]:
        series = []
        for s in DP_ORDER:
            style, fill, lab = pgf.METHOD[s]
            d = r["D2"]["curves"][key_of(s)]
            series.append((style, fill, None, eps, d["mean"], d["std"]))
        write(outdir, f"dp_weights_{panel}.tex", pgf.line_axis(
            series, r"privacy budget $\epsilon$ per query",
            "test accuracy (\\%)", xmode="log"))

    # D3: allocation
    alloc = [("uniform", "vpeEqual", "vpeGrayLight", "Uniform"),
             ("budget_prop_margin_oracle", "vpeCRH", "vpeBlue",
              r"budget $\propto$ margin (exact)"),
             ("budget_prop_margin_released", "vpeRegression", "vpeSky",
              r"budget $\propto$ margin (released)"),
             ("noise_prop_margin_oracle", "vpeLOO", "vpeVermillion",
              r"noise $\propto$ margin (exact)"),
             ("noise_prop_margin_released", "vpeEntropy", "vpePink",
              r"noise $\propto$ margin (released)")]
    series = [(st, fill, lab, r["D3"]["eps_total_grid"],
               r["D3"]["curves"][k]["mean"], r["D3"]["curves"][k]["std"])
              for k, st, fill, lab in alloc]
    write(outdir, "dp_allocation.tex", pgf.line_axis(
        series, r"total privacy budget $\epsilon$ per query",
        "test accuracy (\\%)", xmode="log", width=r"0.8\linewidth",
        height=r"0.55\linewidth", legend_pos="north west"))

    # D4 left: entropy vs margin scatter with flip-rate labels
    pt = r["D4"]["per_teacher"]
    pts = pgf.coords(pt["mean_entropy"], pt["mean_margin"])
    nodes = "\n".join(
        f"\\node[font=\\tiny, gray, anchor=west] at (axis cs:"
        f"{e + 0.03:.4g},{m + 0.012:.4g}) {{{fr:.1f}}};"
        for e, m, fr in zip(pt["mean_entropy"], pt["mean_margin"],
                            r["flip_rates"]))
    body = ("\\begin{tikzpicture}\n"
            "\\begin{axis}[vpe axis, width=\\linewidth,"
            " height=0.8\\linewidth,"
            " xlabel={mean prediction entropy $\\bar H_i$},"
            " ylabel={mean top-2 margin $\\bar\\gamma_i$}, xmajorgrids]\n"
            "\\addplot[only marks, vpeBlue, mark=*, mark size=2pt]"
            " coordinates {" + pts + "};\n" + nodes
            + "\n\\end{axis}\n\\end{tikzpicture}\n")
    write(outdir, "dp_margins_scatter.tex", body)

    # D4 right: flip probability, per-teacher noise (log-log)
    series = []
    for s in ["equal", "accuracy", "entropy_conf", "regression"]:
        style, fill, lab = pgf.METHOD[s]
        d = r["D4"][s]["flip_prob_per_teacher"]
        sig = np.asarray(d["sigma"])
        prob = np.asarray(d["prob"])
        keep = (sig >= 5e-3) & (prob > 0)
        series.append((style, fill, lab, sig[keep].tolist(),
                       prob[keep].tolist(), None))
    write(outdir, "dp_margins_flip.tex", pgf.line_axis(
        series, r"per-teacher Gaussian noise scale $\sigma$",
        "decision flip probability", xmode="log",
        height=r"0.8\linewidth", legend_pos="north west",
        extra=["ymode=log"]))

    # LOO/Shapley marginal contributions
    extras = json.load(open(os.path.join(RES_DP, "extras.json")))
    d = extras["marginal_by_coalition_size"]
    sizes = sorted(int(k) for k in d)
    mean_abs = [d[str(s)]["mean_abs"] for s in sizes]
    body = pgf.line_axis(
        [("vpeCRH", "vpeBlue", None, sizes, mean_abs, None)],
        r"coalition size $|S|$",
        r"mean $|v(S\cup\{i\})-v(S)|$",
        width=r"0.62\linewidth", height=r"0.42\linewidth",
        extra=["ymode=log"])
    write(outdir, "loo_shapley_marginals.tex", body)


# -------------------------------------------------- timing, anomaly extras

RES_TIMING = os.path.join(HERE, "..", "results", "timing",
                          "mnist_times.json")
RES_ANOMALY = os.path.join(HERE, "..", "results", "mnist_anomaly",
                           "anomaly.json")


def make_timing(outdir):
    if not os.path.exists(RES_TIMING):
        print("skipped times_mnist.tex (run experiments/mnist_timing.py)")
        return
    with open(RES_TIMING) as f:
        d = json.load(f)
    series = []
    for m in ["loo", "accuracy", "crh", "entropy", "shapley",
              "regression"]:
        style, fill, lab = pgf.METHOD[m]
        series.append((style, fill, lab, d["sizes"], d["median"][m],
                       None))
    # extra y headroom so the north-west legend clears the regression curve
    write(outdir, "times_mnist.tex", pgf.line_axis(
        series, "Number of Models", "Time (s)", ymax=5000,
        legend_pos="north west",
        extra=("ymode=log",
               "legend style={font=\\scriptsize, fill opacity=0.8,"
               " text opacity=1}")))


def _pow10_scale(values, target=50.0):
    k = int(np.floor(np.log10(target / np.mean(values))))
    prefix = "" if k == 0 else "$10\\times{}$" if k == 1 \
        else f"$10^{{{k}}}\\times{{}}$"
    return 10.0 ** k, prefix


def make_anomaly(outdir):
    if not os.path.exists(RES_ANOMALY):
        print("skipped anomaly figures (run experiments/mnist_anomaly.py)")
        return
    with open(RES_ANOMALY) as f:
        d = json.load(f)
    inst = d["instance"]
    for tag, key, label, fill in [
            ("entropy", "entropy_w", "inverse-entropy power", "vpePink"),
            ("crh", "crh_w", "CRH power", "vpeBlue")]:
        w = np.asarray(inst[key], float)
        scale, prefix = _pow10_scale(w)
        write(outdir, f"anomaly_{tag}.tex", pgf.grouped_bars(
            inst["k"],
            [("vpeGrayLight", "Accuracy (\\%)", inst["accuracy"]),
             (fill, prefix + label, (scale * w).tolist())],
            "Number of classes interchanged", "", ymax=100))
    for mode in ["random", "deterministic"]:
        boxes = [(lab, [(fill, np.asarray(d["corr"][mode][m], float),
                         None)])
                 for m, lab, fill in [
                     ("entropy", "Inverse entropy", "vpePink"),
                     ("crh", "CRH", "vpeBlue")]]
        write(outdir, f"corr_{mode}.tex", pgf.grouped_boxplots(
            boxes, "", "Correlation coefficient",
            ymin=-1.05, ymax=1.05, height=r"0.72\linewidth"))


# ------------------------------------------------------------------ legends

def make_legends(outdir):
    write(outdir, "legend_methods.tex", pgf.legend_row(
        [(pgf.METHOD[m][0], pgf.METHOD[m][2]) for m in ORDER], columns=4))
    write(outdir, "legend_dp_weights.tex", pgf.legend_row(
        [(pgf.METHOD[m][0], pgf.METHOD[m][2]) for m in DP_ORDER],
        columns=4))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--paper-dir", default=os.path.join(HERE, "pgf_out"))
    args = ap.parse_args()
    os.makedirs(args.paper_dir, exist_ok=True)
    with open(os.path.join(args.paper_dir, "..", "pgfstyle.tex"), "w") as f:
        f.write(pgf.STYLE)
    print("wrote pgfstyle.tex")
    make_legends(args.paper_dir)
    make_mnist(args.paper_dir)
    make_datasets(args.paper_dir)
    make_dp(args.paper_dir)
    make_timing(args.paper_dir)
    make_anomaly(args.paper_dir)
